apiVersion: v1
kind: Service
metadata:
  name: alkylates-backend-test
  labels:
    app: alkylates-backend-test
spec:
  type: NodePort
  selector:
    app: alkylates-backend-test
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32122
---
apiVersion: v1
kind: Service
metadata:
  name: alkylates-frontend-test
  labels:
    app: alkylates-frontend-test
spec:
  type: NodePort
  selector:
    app: alkylates-frontend-test
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alkylates-backend-test
  labels:
    app: alkylates-backend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkylates-backend-test
  template:
    metadata:
      labels:
        app: alkylates-backend-test
    spec:
  
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      containers:
        - image: sasoldevchemicalsdigitalreg.azurecr.io/alkylates-backend:test
          name: alkylates-backend-test
          command: ["/app/entrypoint.sh"]
          args: ["gunicorn", "alkylates.wsgi:application", "--bind", "0.0.0.0:8000"]
          imagePullPolicy: IfNotPresent

    
          # envFrom:
          # - secretRef:
          #     name: alkylates-test-secret

          ports:
            - containerPort: 8000
              name: gunicorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alkylates-frontend-test
  labels:
    app: alkylates-frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkylates-frontend-test
  template:
    metadata:
      labels:
        app: alkylates-frontend-test
    spec:
  
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      containers:
        - image: sasoldevchemicalsdigitalreg.azurecr.io/alkylates-frontend:test
          name: alkylates-frontend-test
          command: ["nginx"]
          args: ["-g", "daemon off;"]
          imagePullPolicy: IfNotPresent
    

          ports:
            - containerPort: 80
              name: nginx
